apiVersion: v1
kind: Service
metadata:
  name: arcade-blast-service
  namespace: default
spec:
  selector:
    app: arcade-blast
  type: NodePort
  ports:
  - port: 80           # Port inside the cluster
    targetPort: 80     # Port on the container
    nodePort: 30080    # Exposed on the node (range: 30000â€“32767)
