apiVersion: v1
kind: Service
metadata:
  name: space-invaders-service
  labels:
    app: space-invaders
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
  - name: websocket
    port: 9999
    targetPort: 9999
    nodePort: 30999
  selector:
    app: space-invaders
---
apiVersion: v1
kind: Service
metadata:
  name: space-invaders-loadbalancer
  labels:
    app: space-invaders
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: websocket
    port: 9999
    targetPort: 9999
  selector:
    app: space-invaders
